### PR TITLE
Custom label markup

### PR DESCRIPTION
**Pull request by ghost**
Hi, 

great plugin, however, I want to customize the markup of the footnotes label which currently is hard coded to 

```html
<div class="easy-footnote-title">
  <h4>...</h4>
</div>
```

This pull request allows for the definition of custom label markup in the following way: 

```html
<h2>{{label}}</h2>
```

The placeholder `{{label}}` is replaced by the defined label value. 

Would be great if you could consider this. 

Thanks, Matthias

### CODE REVIEW

**Comment by ghost** [comment]
I solved the conflicts introduced during the last commits to the master branch. 

Anyway, I saw that you introduced an `efn_footnote_label` callback which allows the creation of a filter to completely customize the footnotes labels markup by adding a filter: 

```php 
add_filter("efn_footnote_label", "footnote_label_filter", 1);

function footnote_label_filter($footnote_label) {
  $footnote_label = "<h2>Lorem Ipsum</h2>";
  return $footnote_label;
}
```

This solves the issue addressed with this pull request, however it would be great also to get rid of the `<div class="easy-footnote-title">` wrapper. A corresponding pull request can be found [here](https://github.com/yingles/easy-footnotes/pull/5).

**Comment by jasonyingling** [comment]
Just FYI the `efn_footnote_label` filter can take 2 arguments. So you can still set the label in the backend. The first argument is the full markup and the second is the label text. So you could use:

```php
function efn_change_label_markup( $output, $label ) {
    return '<h2>' . $label . '</h2>';
}
add_filter( 'efn_footnote_label', 'change_efn_label', 10, 2 );
```

**Comment by ghost** [comment]
> Just FYI the `efn_footnote_label` filter can take 2 arguments. So you can still set the label in the backend. The first argument is the full markup and the second is the label text. 

Good to know. Thanks for this information.

In any case, I think this pull request has been rendered obsolete by now since the requested functionality has already been integrated.

**Comment by jasonyingling** [comment]
Glad this works for your case and thanks for submitting the request. Closing now but feel free to open with any updates.

**Pull request closed without merging**
